repos:
-   repo: local
    hooks:
    - id: ruff-format
      stages: [commit]
      name: format code
      language: system
      entry: ruff format .
      types: [python]
    - id: ruff-check
      stages: [commit]
      name: check format,import
      language: system
      entry: ruff check .
      types: [python]
    - id: reuse
      stages: [commit]
      name: reuse
      description: Check licenses
      entry: reuse lint
      pass_filenames: false
      language: system
    - id: gitlint
      stages: [commit-msg]
      name: gitlint
      description: Validate commit lint
      entry: gitlint --msg-filename
      language: system

